
export const tagBackground = {
    grass: "bg-green-500",
    poison: "bg-violet-500",
    fire: "bg-orange-600",
    flying: "bg-purple-600",
    water: "bg-blue-600", 
    bug: "bg-lime-700",
    normal: "bg-teal-500",
    electric: "bg-yellow-300",
    ground: "bg-amber-500", 
    fairy: "bg-red-500",
    fighting: "bg-red-700",
    psychic: "bg-red-300",
    rock: "bg-yellow-600",
    steel: "bg-gray-500",
    ice: "bg-sky-300",
    ghost: "bg-indigo-400",
    dragon: "bg-purple-800",
  }
  
  export const tagColor = {
    grass: "text-black",
    poison: "text-white",
    fire: "text-white",
    flying: "text-white",
    water: "text-white", 
    bug: "text-white",
    normal: "text-white",
    electric: "text-black",
    ground: "text-black", 
    fairy: "text-white",
    fighting: "text-white",
    psychic: "text-black",
    rock: "text-white",
    steel: "text-white",
    ice: "text-black",
    ghost: "text-black",
    dragon: "text-white",
  }
  