export const actionTypes = {
    SET_POKEMONS: "SET_POKEMONS",
    APPEND_POKEMONS: "APPEND_POKEMONS",
    SET_POKEMON_FILTER: "SET_POKEMON_FILTER",
    SET_FILTERED_POKEMONS: "SET_FILTERED_POKEMONS"
}
