export const actionTypes = {
    SET_POKEMONS: "SET_POKEMONS",
    APPEND_POKEMONS: "APPEND_POKEMONS",
    SET_POKEMON_FILTER: "SET_POKEMON_FILTER",
    SET_FILTERED: "SET_FILTERED",
    SET_PAGE: "SET_PAGE"
}
